local k = vim.keymap.set
local function n(m, f, d)
	k("n", m, f, { desc = d or f })
end
vim.ui.select = require("mini.pick").ui_select
n(",o", "<CMD>AerialToggle<CR>", "Aerial")
n("-", "<CMD>Oil<CR>", "Open pwd")
n("<leader>fs", "1z=", "Fix spelling under cursor")
n("<space>ff", "<CMD>lua MiniFiles.open()<CR>")
n(",f", "<CMD>lua MiniFiles.open()<CR>", "files")
n("<space>fb", "<CMD>lua MiniExtra.pickers.buffers()<CR>", "buffers")
n(",b", "<CMD>lua MiniExtra.pickers.buffers()<CR>", "buffers")
n("<space>fd", "<CMD>lua MiniExtra.pickers.diagnostic()<CR>", "diagnostic")
n(",e", "<CMD>lua MiniExtra.pickers.explorer()<CR>", "explorer")
n("<space>fo", "<CMD>lua MiniExtra.pickers.history()<CR>", "history")
n("<space>fr", "<CMD>lua MiniExtra.pickers.history()<CR>", "history")
n("<space>fl", "<CMD>lua MiniExtra.pickers.lsp()<CR>", "lsp")
n(",c", "<CMD>lua MiniExtra.pickers.lsp()<CR>", "lsp")
n("<space>e", "<CMD>lua MiniFiles.open()<CR>", "files")
n("0", "^")
n("<leader>fe", "mc:%s,\\.\\.\\.,…,g<CR>:nohlsearch<CR>`c", "… -> …")
n(";", ":")
n("<space>vp", "<CMD>e ~/.config/ec/lua/plugin.lua<CR>", "plugin.lua")
n("<space>vk", "<CMD>e ~/.config/ec/lua/keymap.lua<CR>", "keymap.lua")
n("<space>vo", "<CMD>e ~/.config/ec/lua/opts.lua<CR>", "opts.lua")
n("<space>vi", "<CMD>e ~/.config/ec/init.lua<CR>", "init.lua")
n("H", "<esc>:bp<CR>")
n("L", "<esc>:bn<CR>")
n(",v", "<CMD>e ~/.config/ec/init.lua<CR>", "init.lua")
n("<space>so", "<CMD>sso %C<CR)>")
n(",s", "<CMD>sso %C<CR)>")
k({ "c", "i" }, "<c-a>", "<home>")
k({ "c", "i" }, "<c-e>", "<end>")
k({ "c", "i" }, "<c-f>", "<right>")
k({ "c", "i" }, "<c-b>", "<left>")
k({"n", "i", "t", "v"}, "<c-j>", "<c-w>j")
k({"n", "i", "t", "v"}, "<c-h>", "<c-w>h")
k({"n", "i", "t", "v"}, "<c-k>", "<c-w>k")
k({"n", "i", "t", "v"}, "<c-l>", "<c-w>l")
k("t", "<c-p>", "<up>", { silent = true, nowait = true, noremap = true })
k("t", "<c-n>", "<down>", { silent = true, nowait = true, noremap = true })
