local o = vim.opt
local g = vim.g
o.cmdheight = 0
g.loaded_netrw = 1
g.loaded_netrwPlugin = 1
o.autowrite = true
o.autoread = true
o.autowriteall = true
g.mapleader = " "
o.confirm = false
o.warn = false
o.clipboard = "unnamedplus"
g.maplocalleader = ","
o.signcolumn = "yes:1"
o.winborder = nil
o.expandtab = true
o.autoindent = true
o.tabstop = 2
o.softtabstop = 2
o.shiftwidth = 2
o.number = true
o.relativenumber = true
o.numberwidth = 2
o.completeopt = { "menuone", "popup", "noinsert" }
o.hlsearch = true
o.termguicolors = true
o.inccommand = "nosplit"
o.undofile = true
o.cursorline = true
o.swapfile = false
o.undodir = os.getenv("HOME") .. "/.vim/undodir"
o.incsearch = true
o.shiftround = true
o.showtabline = 3
o.laststatus = 3
g.copilot_no_tab_map = false
g.loaded_matchit = 1
-- g.loaded_matchparen = 1
g.loaded_netrw = 1
g.loaded_netrwPlugin = 1
