local o = vim.opt
local g = vim.g

o.autochdir = true
o.hlsearch = true
o.backup = false
o.clipboard = "unnamedplus"
o.cmdheight = 1
o.completeopt = { "menuone", "noselect" }
o.conceallevel = 0
o.fileencoding = "utf-8"
o.mouse = "a"
o.scrolloff = 8
o.cursorline = true
o.splitbelow = true
o.splitright = true
o.backup = false
o.swapfile = false
o.undofile = false
o.pumblend = 10
o.winblend = 10
o.autochdir = false
o.signcolumn = "yes"
o.incsearch = true

o.number = true
o.expandtab = true
o.softtabstop = 2
o.tabstop = 2
o.shiftwidth = 2
o.relativenumber = true
o.laststatus = 3
o.showtabline = 3
o.wildignorecase = true
o.breakindent = true
o.smartindent = true
o.infercase = true
o.wrap = true
o.ignorecase = true
o.smartcase = true
o.timeoutlen = 300
o.inccommand = "split"
o.signcolumn = "yes"
o.smoothscroll = true

g.mapleader = " "
g.maplocalleader = ","
vim.env.PATH = vim.env.HOME .. "/.local/share/mise/shims:" .. vim.env.PATH
