  vim.o.termguicolors = true
  vim.o.autochdir = true
  vim.o.grepprg = 'rg --vimgrep'
  vim.o.makeprg = 'make'
  vim.o.pumblend = 12
  vim.o.winblend = 15
  vim.o.number = true
  vim.o.relativenumber = true
  vim.o.wrap = true
  vim.o.laststatus=3
  vim.o.signcolumn='yes'
  vim.o.cursorline=true
  vim.o.autoindent=true
  vim.o.ignorecase=true
  vim.o.infercase=true
  vim.o.gdefault = true
  vim.o.hidden = true
  vim.o.hlsearch = true
  vim.o.incsearch = true
  vim.o.mouse = 'a'
  vim.o.scrolloff = 5
  vim.o.sidescrolloff = 5
  vim.o.ts=2
  vim.o.sts=2
  vim.o.sw=2
  vim.o.et=true
  vim.o.smarttab=true
  vim.o.smartcase=true
  vim.o.showtabline=3
  vim.o.laststatus=3
  vim.o.showtabline=3
  vim.o.showmatch=true
  vim.g.mapleader = ' '
  vim.g.maplocalleader = ','
