local range = vim.version.range
local gh, dev = require("util").gh, require("util").dev

---@type vim.pack.Spec[]
return {
  gh("folke/sidekick.nvim"),
  gh("Davidyz/VectorCode"),
  gh("m-demare/hlargs.nvim"),
  gh("folke/persistence.nvim"),
	gh("pwntester/octo.nvim", nil, require("plugins.octo")),
  gh("milanglacier/minuet-ai.nvim"),
	gh("rachartier/tiny-inline-diagnostic.nvim"),
	gh("sourcegraph/amp.nvim"),
	gh("stevearc/oil.nvim"),
	gh("stevearc/aerial.nvim"),
	gh("nvim-mini/mini.icons"),
	gh("nvim-mini/mini.doc"),
	gh("nvim-mini/mini.test"),
	gh("nvim-mini/mini.bufremove"),
	gh("nvim-mini/mini.starter"),
	gh("nvim-mini/mini.cursorword"),
	gh("isakbm/gitgraph.nvim"),
	gh("OXY2DEV/markview.nvim"),
	gh("CopilotC-Nvim/CopilotChat.nvim"),
	gh("ThePrimeagen/git-worktree.nvim"),
	gh("MagicDuck/grug-far.nvim"),
	gh("greggh/claude-code.nvim"),
	gh("xzbdmw/colorful-menu.nvim"),
	gh("sindrets/diffview.nvim"),
	gh("onsails/lspkind.nvim"),
	gh("EdenEast/nightfox.nvim"),
	gh("ravitemer/mcphub.nvim"),
	gh("catppuccin/nvim"),
	gh("Bekaboo/dropbar.nvim"),
	gh("olimorris/codecompanion.nvim"),
	gh("folke/which-key.nvim"),
	gh("folke/edgy.nvim"),
	gh("folke/ts-comments.nvim"),
	gh("folke/todo-comments.nvim"),
	gh("NeogitOrg/neogit"),
	gh("folke/trouble.nvim"),
	gh("nvim-tree/nvim-web-devicons"),
	gh("romgrk/barbar.nvim"),
	gh("SmiteshP/nvim-navic"),
	gh("nvim-lua/plenary.nvim"),
	gh("stevearc/overseer.nvim"),
	gh("stevearc/conform.nvim"),
	gh("nvim-lualine/lualine.nvim"),
	gh("nvim-telescope/telescope.nvim"),
	gh("nvim-telescope/telescope-fzf-native.nvim"),
	gh("neovim/nvim-lspconfig"),
	gh("ray-x/go.nvim"),
	gh("j-hui/fidget.nvim"),
	gh("saghen/blink.cmp", range("^1")),
	gh("folke/neoconf.nvim"),
	gh("folke/lazydev.nvim"),
	gh("RRethy/nvim-treesitter-endwise"),
	gh("folke/snacks.nvim"),
	gh("b0o/schemastore.nvim"),
	gh("mason-org/mason.nvim"),
	gh("mason-org/mason-lspconfig.nvim"),
	gh("nvim-treesitter/nvim-treesitter"),
	gh("nvim-treesitter/nvim-treesitter-context"),
	gh("nvim-treesitter/nvim-treesitter-textobjects"),
	gh("github/copilot.vim"),
	gh("lewis6991/gitsigns.nvim"),
	gh("windwp/nvim-autopairs"),
	gh("windwp/nvim-ts-autotag"),
	-- dev("/Users/clp/clp/down.nvim"),
	-- gh("lukas-reineke/headlines.nvim"),
  -- gh("zbirenbaum/copilot.lua", nil, require("plugins.copilot")),
	-- gh("nvim-tree/nvim-tree.lua"),
	-- gh("akinsho/toggleterm.nvim"),
	-- gh "SmiteshP/nvim-navbuddy",
	-- gh "piersolenski/wtf.nvim",
	-- gh "nvim-neotest/neotest",
	-- gh "yetone/avante.nvim",
	-- gh "nanozuki/tabby.nvim",
	-- gh "ThePrimeagen/refactoring.vim" ,
	-- gh "clpi/down.nvim" ,
}
