local range = vim.version.range
local gh, dev = require("util").gh, require("util").dev

---@type vim.pack.Spec[]
return {
	gh("MunifTanjim/nui.nvim"),
	gh("HakonHarnes/img-clip.nvim"),
	gh("folke/sidekick.nvim"),
	-- gh("m/mrcjkb/rustaceanvim"),
	gh("folke/flash.nvim"),
	gh("folke/sidekick.nvim", nil, require("plugins.sidekick")),
	gh("Davidyz/VectorCode", nil, require("plugins.vectorcode")),
	gh("m-demare/hlargs.nvim", nil, require("plugins.hlargs")),
	gh("folke/persistence.nvim", nil, require("plugins.persistence")),
	gh("pwntester/octo.nvim", nil, require("plugins.octo")),
	gh("milanglacier/minuet-ai.nvim", nil, require("plugins.minuet-ai")),
	gh("rachartier/tiny-inline-diagnostic.nvim"),
	gh("sourcegraph/amp.nvim"),
	gh("stevearc/oil.nvim"),
	gh("stevearc/aerial.nvim"),
	gh("nvim-mini/mini.icons"),
	gh("nvim-mini/mini.animate"),
	-- gh("nvim-mini/mini.indentscope"),
	gh("nvim-mini/mini.test"),
	gh("nvim-mini/mini.bufremove"),
	gh("nvim-mini/mini.starter"),
	gh("nvim-mini/mini.cursorword"),
	gh("isakbm/gitgraph.nvim"),
	gh("OXY2DEV/markview.nvim"),
	gh("CopilotC-Nvim/CopilotChat.nvim"),
	gh("ThePrimeagen/git-worktree.nvim"),
	gh("MagicDuck/grug-far.nvim"),
	gh("coder/claudecode.nvim"),
	gh("xzbdmw/colorful-menu.nvim"),
	gh("sindrets/diffview.nvim"),
	gh("onsails/lspkind.nvim"),
	gh("EdenEast/nightfox.nvim"),
	gh("ravitemer/mcphub.nvim"),
	gh("Bekaboo/dropbar.nvim"),
	gh("olimorris/codecompanion.nvim"),
	gh("folke/which-key.nvim"),
	gh("folke/edgy.nvim"),
	gh("folke/ts-comments.nvim"),
	gh("folke/todo-comments.nvim"),
	gh("NeogitOrg/neogit"),
	gh("folke/trouble.nvim"),
	gh("nvim-tree/nvim-web-devicons"),
	gh("romgrk/barbar.nvim"),
	gh("SmiteshP/nvim-navic"),
	gh("nvim-lua/plenary.nvim"),
	gh("stevearc/overseer.nvim"),
	gh("ckipp01/nvim-jenkinsfile-linter"),
	gh("stevearc/conform.nvim"),
	gh("nvim-lualine/lualine.nvim"),
	gh("nvim-telescope/telescope.nvim"),
	gh("nvim-telescope/telescope-fzf-native.nvim"),
	gh("neovim/nvim-lspconfig"),
	gh("ray-x/go.nvim"),
	gh("j-hui/fidget.nvim"),
	gh("folke/lazydev.nvim"),
	gh("saghen/blink.cmp", range("^1")),
	gh("folke/neoconf.nvim"),
	gh("RRethy/nvim-treesitter-endwise"),
	gh("folke/snacks.nvim"),
	gh("b0o/schemastore.nvim"),
	gh("mason-org/mason.nvim"),
	gh("mason-org/mason-lspconfig.nvim"),
	gh("nvim-treesitter/nvim-treesitter"),
	gh("nvim-treesitter/nvim-treesitter-context"),
	gh("nvim-treesitter/nvim-treesitter-textobjects"),
	gh("github/copilot.vim"),
	gh("lewis6991/gitsigns.nvim"),
	gh("windwp/nvim-autopairs"),
	gh("yetone/avante.nvim"),
	dev("/Users/clp/clp/down.nvim"),
	-- gh("windwp/nvim-ts-autotag"),
	-- gh("nvim-mini/mini.doc"),
	-- gh("catppuccin/nvim"),
	-- gh("lukas-reineke/headlines.nvim"),
	-- gh("zbirenbaum/copilot.lua", nil, require("plugins.copilot")),
	-- gh("nvim-tree/nvim-tree.lua"),
	-- gh("akinsho/toggleterm.nvim"),
	-- gh "SmiteshP/nvim-navbuddy",
	-- gh "piersolenski/wtf.nvim",
	-- gh "nvim-neotest/neotest",
	-- gh "nanozuki/tabby.nvim",
	-- gh "ThePrimeagen/refactoring.vim" ,
	-- gh "clpi/down.nvim" ,
}
