vim.pack.add(require("plugins.spec"))

require("edgy").setup(require("plugins.edgy"))
require("hlargs").setup(require("plugins.hlargs"))
require("sidekick").setup(require("plugins.sidekick"))
require("vectorcode").setup(require("plugins.vectorcode"))
require("persistence").setup(require("plugins.persistence"))
require("treesitter-context").setup({})
require("nvim-treesitter.configs").setup(require("plugins.treesitter"))
require("overseer").setup(require("plugins.overseer"))
require("nvim-autopairs").setup(require('plugins.nvim-autopairs'))
require("telescope").setup(require("plugins.telescope"))
require("lualine").setup(require("plugins.lualine"))
require("conform").setup(require("plugins.conform"))
require("neogit").setup(require("plugins.neogit"))
require("mini.icons").setup({})
require("mini.cursorword").setup({})
require("mini.bufremove").setup({})
require("mini.doc").setup(require("plugins.minidoc"))
require("mini.test").setup(require("plugins.minitest"))
require("nvim-navic").setup(require("plugins.navic"))
require("grug-far").setup(require("plugins.grug-far"))
require("blink.cmp").setup(require("plugins.blink"))
require("mason").setup(require("plugins.mason"))
require("mason-lspconfig").setup({})
require("snacks").setup(require("plugins.snacks"))
require("colorful-menu").setup(require("plugins.colorful-menu"))
require("lazydev").setup(require("plugins.lazydev"))
require("neoconf").setup(require("plugins.neoconf"))
require("gitsigns").setup(require("plugins.gitsigns"))
require("gitgraph").setup(require("plugins.gitgraph"))
require("trouble").setup(require('plugins.trouble'))
require("which-key").setup(require("plugins.which-key"))
require("ts-comments").setup(require("plugins.ts-comments"))
require("todo-comments").setup(require("plugins.todo-comments"))
require("markview").setup(require("plugins.markview"))
require("mcphub").setup(require("plugins.mcphub"))
require("codecompanion").setup(require("plugins.codecompanion"))
require("barbar").setup(require("plugins.barbar"))
require("dropbar").setup(require("plugins.dropbar"))
require("amp").setup(require("plugins.amp"))
require("oil").setup(require("plugins.oil"))
require("aerial").setup(require('plugins.aerial'))
require("fidget").setup(require("plugins.fidget"))
require("diffview").setup(require('plugins.diffview'))
require("git-worktree").setup(require("plugins.git-worktree"))
require("tiny-inline-diagnostic").setup(require("plugins.tiny-inline-diagnostic"))
require("claude-code").setup(require("plugins.claude-code"))
require("octo").setup(require("plugins.octo"))
require("CopilotChat").setup(require("plugins.copilotchat"))
require("mini.starter").setup(require("plugins.ministarter"))
require("nightfox").setup(require("plugins.nightfox"))
-- require("down").setup(require("plugins.down"))
-- require("headlines").setup({})
-- require("nvim-tree").setup({})
-- require("minuet-ai").setup(require("plugins.minuet-ai"))
-- require("toggleterm").setup(require("plugins.toggleterm"))
-- require("wtf").setup({})
-- require("avante").setup(require("plugins.avante"))
-- require("tabby").setup({})
-- require("catppuccin").setup(require("plugins.catppuccin"))
-- require("noice").setup({})
-- require("refactoring").setup({})
-- require("neotest").setup({})
-- require("nvim-navbuddy").setup({})
